import { Link } from 'react-router-dom';
import { LegalLayout, LegalSection } from '@/components/legal/LegalLayout';

const UPDATED_AT = 'August 13, 2026';
const CONTACT_EMAIL = 'joinetra@gmail.com';

export function TermsOfServicePage() {
  return (
    <LegalLayout title="Terms of Service" updatedAt={UPDATED_AT}>
      <p>
        These Terms of Service ("Terms") govern access to and use of Joinetra, a CRM platform for
        travel agencies to manage leads, bookings, and customer communication ("Service"). By
        creating an account or using the Service, you agree to these Terms on behalf of yourself
        and the organization you represent.
      </p>

      <LegalSection heading="1. Who can use Joinetra">
        <p>
          Joinetra is intended for use by travel agencies and their team members. You must provide
          accurate information when creating an account and are responsible for keeping your
          login credentials confidential. Your organization's admin is responsible for managing
          which team members have access.
        </p>
      </LegalSection>

      <LegalSection heading="2. Your data, your business">
        <p>
          Data you enter into Joinetra — leads, bookings, customer contacts, messages, packages,
          itineraries — belongs to your organization. We process it to provide the Service to you
          and don't use it for our own marketing or sell it to third parties. Each organization's
          data is kept isolated from every other organization on the platform.
        </p>
      </LegalSection>

      <LegalSection heading="3. Connected channels (WhatsApp, Instagram, Email)">
        <p>
          If you connect a WhatsApp Business number, Instagram account, or email inbox, you're
          responsible for having the right to use that number/account/inbox for business
          messaging, and for complying with the connected platform's own policies (for example,
          Meta's WhatsApp Business and Instagram Platform policies, and applicable anti-spam laws).
          Joinetra may suspend a connected channel if we're notified by the platform provider of a
          policy violation.
        </p>
      </LegalSection>

      <LegalSection heading="4. Acceptable use">
        <p>You agree not to use Joinetra to:</p>
        <ul className="list-disc space-y-2 pl-5">
          <li>Send unsolicited bulk messages or spam through any connected channel.</li>
          <li>Upload or transmit unlawful, fraudulent, or infringing content.</li>
          <li>Attempt to access another organization's data or bypass tenant isolation.</li>
          <li>Reverse-engineer, scrape, or resell the Service without our written permission.</li>
          <li>Interfere with the Service's security, availability, or normal operation.</li>
        </ul>
      </LegalSection>

      <LegalSection heading="5. AI features">
        <p>
          Optional AI-assisted features (reply suggestions, summaries, automated bot replies) are
          generated by a third-party AI provider your organization configures. AI output can be
          inaccurate — you're responsible for reviewing AI-generated content before it's sent to a
          real customer, especially anything involving pricing, dates, or commitments.
        </p>
      </LegalSection>

      <LegalSection heading="6. Third-party services">
        <p>
          Joinetra relies on third-party providers (including Meta's WhatsApp/Instagram APIs,
          Google Gemini, Resend, Supabase, and our hosting provider) to deliver parts of the
          Service. We're not responsible for outages, policy changes, or service interruptions
          originating from these providers, though we'll do our best to keep you informed.
        </p>
      </LegalSection>

      <LegalSection heading="7. Availability">
        <p>
          We aim to keep Joinetra available and reliable but don't guarantee uninterrupted access.
          We may perform maintenance, and features may change as the product evolves.
        </p>
      </LegalSection>

      <LegalSection heading="8. Termination">
        <p>
          You may stop using the Service and request deletion of your organization's account at
          any time by emailing{' '}
          <a href={`mailto:${CONTACT_EMAIL}`} className="text-primary underline-offset-2 hover:underline">
            {CONTACT_EMAIL}
          </a>. We may suspend or terminate access if these Terms are violated, particularly around
          acceptable use of connected messaging channels.
        </p>
      </LegalSection>

      <LegalSection heading="9. Disclaimer &amp; limitation of liability">
        <p>
          The Service is provided "as is." To the fullest extent permitted by law, Joinetra isn't
          liable for indirect, incidental, or consequential damages arising from your use of the
          Service, including issues caused by third-party platforms we integrate with.
        </p>
      </LegalSection>

      <LegalSection heading="10. Changes to these Terms">
        <p>
          We may update these Terms as the product evolves. Continued use of the Service after an
          update means you accept the revised Terms. Material changes will be reflected by updating
          the "Last updated" date above.
        </p>
      </LegalSection>

      <LegalSection heading="11. Contact us">
        <p>
          Questions about these Terms? Email{' '}
          <a href={`mailto:${CONTACT_EMAIL}`} className="text-primary underline-offset-2 hover:underline">
            {CONTACT_EMAIL}
          </a>.
        </p>
        <p>
          See also our{' '}
          <Link to="/privacy" className="text-primary underline-offset-2 hover:underline">
            Privacy Policy
          </Link>.
        </p>
      </LegalSection>
    </LegalLayout>
  );
}
